#新加任务需要把名字添加到fact_whaley.job的dependencies配置中
#详情页浏览
type=command
table=fact_whaley_detail
mainclass=cn.whaley.datawarehouse.fact.whaley.DetailView
command=echo 'success ...'
command=sh ${working.dir}/../../../bin/fact_submit.sh ${mainclass} --startDate ${startDate} --endDate ${endDate} --isOnline  ${isOnline}
command.1=sh ${working.dir}/../../../bin/addPartition.sh --table ${table} --startDate ${startDate} --endDate ${endDate}  --hour ${hour}
