#新加任务需要把名字添加到fact_medusa.job的dependencies配置中
type=command
table=fact_medusa_play_quality
mainclass=cn.whaley.datawarehouse.fact.moretv.PlayQuality
command=sh ${working.dir}/../../bin/fact_submit.sh ${mainclass} --startDate ${startDate} --endDate ${endDate} --startHour ${startHour} --endHour ${endHour}  --isOnline  ${isOnline}
command.1=sh ${working.dir}/../../bin/addPartition.sh --table ${table} --startDate ${startDate} --endDate ${endDate} --startHour ${startHour} --endHour ${endHour} --isOnline  ${isOnline}